"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('EXP_EXAMPLE_CAMPAIGN_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('EXP_EXAMPLE_CAMPAIGN_DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.postgres',
    'corsheaders',
]

THIRD_PARTY_APP = [
    'rest_framework',
    'qrcode',
]

LOCAL_APPS = [
    'campaign',
]

INSTALLED_APPS += THIRD_PARTY_APP + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

APP_VERSION = [
    'v1',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'example.urls'

WSGI_APPLICATION = 'example.wsgi.application'

### REST FRAMEWORK SETTING ###
'''
Namespaces are one honking great idea - let's do more of those!

Configuration for REST framework is all namespaced inside a
single Django setting, named REST_FRAMEWORK.

If you need to access the values of REST framework's API
settings in your project, you should use the api_settings
object.

from rest_framework.settings import api_settings
'''
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'example.core.renderers.ApiRenderer',
    ),
    'EXCEPTION_HANDLER': 'example.core.exceptions.api_exception_handler',
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('EXP_EXAMPLE_CAMPAIGN_DATABASE_NAME'),
        'USER': os.environ.get('EXP_EXAMPLE_CAMPAIGN_DATABASE_USERNAME'),
        'PASSWORD': os.environ.get('EXP_EXAMPLE_CAMPAIGN_DATABASE_PASSWORD'),
        'HOST': os.environ.get('EXP_EXAMPLE_CAMPAIGN_DATABASE_HOST'),
        'PORT': os.environ.get('EXP_EXAMPLE_CAMPAIGN_DATABASE_PORT'),
    }
}


AWS_STORAGE_BUCKET_NAME = os.environ.get('EXP_EXAMPLE_CAMPAIGN_AWS_STORAGE_BUCKET_NAME')
S3DIRECT_REGION = os.environ.get('EXP_EXAMPLE_CAMPAIGN_S3DIRECT_REGION')
AWS_ACCESS_KEY_ID = os.environ.get('EXP_EXAMPLE_CAMPAIGN_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('EXP_EXAMPLE_CAMPAIGN_AWS_SECRET_ACCESS_KEY')
AWS_IMAGE_URL = os.environ.get('EXP_EXAMPLE_CAMPAIGN_AWS_IMAGE_URL')
AWS_STORE_CAMPAIGN_PATH = os.environ.get('EXP_EXAMPLE_CAMPAIGN_AWS_STORE_CAMPAIGN_PATH')

EXP_EXAMPLE_USER_KAFKA_SERVER = os.environ.get('EXP_EXAMPLE_USER_KAFKA_SERVER')
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800

TIME_ZONE = 'UTC'

ENABLE_KAFKA = os.environ.get('EXP_EXAMPLE_CAMPAIGN_ENABLE_KAFKA')

EMAIL_DEFAULT = os.environ.get('EXP_EXAMPLE_USER_EMAIL_DEFAULT')
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'XXXXXXXXXXX@XXXXXXXXXXX.com'
EMAIL_HOST_PASSWORD = 'XXXXXXXXXXXXXXX'
EMAIL_PORT = 25

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]